# Generated by Django 6.0.2 on 2026-06-09 19:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('numero_telephone', models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone')),
                ('est_un_compte_patient', models.BooleanField(default=False, verbose_name='Compte patient')),
                ('est_un_compte_medecin', models.BooleanField(default=False, verbose_name='Compte médecin')),
                ('est_un_compte_pharmacien', models.BooleanField(default=False, verbose_name='Compte pharmacien')),
                ('fcm_token', models.TextField(blank=True, null=True, verbose_name='Token FCM')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('LIVRE', 'Livré')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('methode_retrait', models.CharField(default='RETRAIT', max_length=50, verbose_name='Méthode de retrait')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID transaction')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(verbose_name='Diagnostic')),
                ('actes_effectues', models.TextField(verbose_name='Actes effectués')),
                ('notes_medecin', models.TextField(blank=True, null=True, verbose_name='Notes du médecin')),
                ('date_consultation', models.DateTimeField(auto_now_add=True, verbose_name='Date consultation')),
                ('document_joint', models.FileField(blank=True, null=True, upload_to='consultations/documents/', verbose_name='Document joint')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('coordonnee_latitude_gps', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude GPS')),
                ('coordonnee_longitude_gps', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude GPS')),
                ('plage_horaire_ouverture', models.CharField(max_length=100, verbose_name='Plage horaire')),
                ('image_etablissement', models.ImageField(blank=True, null=True, upload_to='etablissements/', verbose_name='Image')),
                ('type_urgences', models.CharField(max_length=100, verbose_name="Type d'urgences")),
                ('liste_services', models.TextField(verbose_name='Liste des services')),
            ],
            options={
                'verbose_name': 'Hôpital',
                'verbose_name_plural': 'Hôpitaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(db_index=True, max_length=100, verbose_name='Nom commercial')),
                ('description', models.TextField(verbose_name='Description')),
                ('posologie_standard', models.TextField(verbose_name='Posologie standard')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='medicaments/', verbose_name='Image du produit')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom_commercial'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('coordonnee_latitude_gps', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude GPS')),
                ('coordonnee_longitude_gps', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude GPS')),
                ('plage_horaire_ouverture', models.CharField(max_length=100, verbose_name='Plage horaire')),
                ('image_etablissement', models.ImageField(blank=True, null=True, upload_to='etablissements/', verbose_name='Image')),
                ('pharmacie_est_garde', models.BooleanField(default=False, verbose_name='Pharmacie de garde')),
                ('numero_paiement', models.CharField(help_text='Numéro T-Money ou Flooz de la pharmacie', max_length=15, verbose_name='Numéro de paiement')),
                ('reseau_paiement', models.CharField(choices=[('tmoney', 'T-Money'), ('flooz', 'Flooz')], default='tmoney', max_length=10, verbose_name='Réseau de paiement')),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField(verbose_name='Date du rendez-vous')),
                ('heure_rdv', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('motif_consultation', models.CharField(max_length=255, verbose_name='Motif')),
                ('statut_actuel_rdv', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('expire', 'Expiré')], default='en_attente', max_length=50, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_rdv', '-heure_rdv'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('specialite_medicale', models.CharField(max_length=100, verbose_name='Spécialité médicale')),
                ('numero_licence', models.CharField(max_length=50, unique=True, verbose_name='Numéro de licence')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/medecins/', verbose_name='Photo de profil')),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'ordering': ['compte_utilisateur__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/patients/', verbose_name='Photo de profil')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['compte_utilisateur__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture_session', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('utilisateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_assistant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session chatbot',
                'verbose_name_plural': 'Sessions chatbot',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_texte', models.TextField(verbose_name='Message')),
                ('envoye_par_utilisateur', models.BooleanField(verbose_name="Envoyé par l'utilisateur")),
                ('heure_message', models.DateTimeField(auto_now_add=True, verbose_name='Heure du message')),
                ('chatbot_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lamessin_app.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['heure_message'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('heure_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Heure d'envoi")),
                ('type_notification', models.CharField(max_length=50, verbose_name='Type')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-heure_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateField(auto_now_add=True, verbose_name='Date de prescription')),
                ('code_securite', models.CharField(max_length=15, null=True, unique=True, verbose_name='Code de sécurité')),
                ('fichier_ordonnance', models.FileField(blank=True, null=True, upload_to='ordonnances/pdf/', verbose_name='Fichier PDF')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.consultation', verbose_name='Consultation')),
                ('medecin_prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medecin', verbose_name='Médecin prescripteur')),
                ('patient_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='DetailOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_boites', models.PositiveIntegerField(default=1, verbose_name='Nombre de boîtes')),
                ('posologie_specifique', models.TextField(verbose_name='Posologie spécifique')),
                ('duree_traitement_jours', models.PositiveIntegerField(verbose_name='Durée (jours)')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament', verbose_name='Médicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='lamessin_app.ordonnance', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': 'Détail ordonnance',
                'verbose_name_plural': 'Détails ordonnances',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.FloatField(verbose_name='Montant total')),
                ('moyen_de_paiement', models.CharField(max_length=50, verbose_name='Moyen de paiement')),
                ('identifiant_transaction_mobile', models.CharField(max_length=100, unique=True, verbose_name='ID transaction mobile')),
                ('confirmation_paiement', models.BooleanField(default=False, verbose_name='Confirmation')),
                ('commande_associee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-commande_associee__date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='lamessin_app.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament', verbose_name='Produit')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.pharmacie', verbose_name='Pharmacie')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='rdv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='lamessin_app.rendezvous', verbose_name='Rendez-vous'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle_en_stock', models.PositiveIntegerField(verbose_name='Quantité en stock')),
                ('seuil_alerte', models.PositiveIntegerField(default=10, verbose_name="Seuil d'alerte")),
                ('date_peremption', models.DateField(verbose_name='Date de péremption')),
                ('pharmacie_detentrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.pharmacie', verbose_name='Pharmacie')),
                ('produit_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-date_peremption'],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_traitement', models.CharField(max_length=100, verbose_name='Nom du traitement')),
                ('date_debut_traitement', models.DateField(verbose_name='Date début')),
                ('date_fin_traitement', models.DateField(verbose_name='Date fin')),
                ('ordonnance_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.ordonnance', verbose_name="Ordonnance d'origine")),
                ('patient_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['-date_debut_traitement'],
            },
        ),
        migrations.CreateModel(
            name='PriseMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_prise_prevue', models.TimeField(verbose_name='Heure prévue')),
                ('prise_effectuee', models.BooleanField(default=False, verbose_name='Prise effectuée')),
                ('date_prise_reelle', models.DateField(verbose_name='Date réelle')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.traitement', verbose_name='Traitement')),
            ],
            options={
                'verbose_name': 'Prise de médicament',
                'verbose_name_plural': 'Prises de médicaments',
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin_concerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medecin', verbose_name='Médecin'),
        ),
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure début')),
                ('heure_fin', models.TimeField(verbose_name='Heure fin')),
                ('duree_consultation', models.PositiveIntegerField(default=60, verbose_name='Durée consultation (min)')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages', to='lamessin_app.medecin', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Plage horaire',
                'verbose_name_plural': 'Plages horaires',
                'ordering': ['-date', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_commandes', to='lamessin_app.patient', verbose_name='Patient'),
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('numero_licence', models.CharField(max_length=50, unique=True, verbose_name='Numéro de licence')),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.pharmacie', verbose_name='Pharmacie')),
            ],
            options={
                'verbose_name': 'Pharmacien',
                'verbose_name_plural': 'Pharmaciens',
                'ordering': ['compte_utilisateur__last_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together={('medecin_concerne', 'date_rdv', 'heure_rdv')},
        ),
    ]
