# Generated by Django 6.0.2 on 2026-03-21 02:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(max_length=15, unique=True)),
                ('est_un_compte_patient', models.BooleanField(default=False)),
                ('est_un_compte_medecin', models.BooleanField(default=False)),
                ('est_un_compte_pharmacien', models.BooleanField(default=False)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('LIVRE', 'Livré')], default='EN_ATTENTE', max_length=20)),
                ('methode_retrait', models.CharField(default='RETRAIT', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('actes_effectues', models.TextField()),
                ('notes_medecin', models.TextField(blank=True, null=True)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('document_joint', models.FileField(blank=True, null=True, upload_to='consultations/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('coordonnee_latitude_gps', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('coordonnee_longitude_gps', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('plage_horaire_ouverture', models.CharField(max_length=100)),
                ('image_etablissement', models.ImageField(blank=True, null=True, upload_to='etablissements/')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('posologie_standard', models.TextField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='medicaments/')),
            ],
            options={
                'verbose_name': 'Médicament',
                'ordering': ['nom_commercial'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('motif_consultation', models.CharField(max_length=255)),
                ('statut_actuel_rdv', models.CharField(default='en_attente', max_length=50)),
            ],
            options={
                'ordering': ['-date_rdv', '-heure_rdv'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite_medicale', models.CharField(max_length=100)),
                ('numero_licence', models.CharField(max_length=50, unique=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/medecins/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/patients/')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_licence', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture_session', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_assistant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('etablissementsante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lamessin_app.etablissementsante')),
                ('type_urgences', models.CharField(max_length=100)),
                ('liste_services', models.TextField()),
            ],
            bases=('lamessin_app.etablissementsante',),
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('etablissementsante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lamessin_app.etablissementsante')),
                ('pharmacie_est_garde', models.BooleanField(default=False)),
                ('numero_paiement', models.CharField(help_text='Numéro T-Money ou Flooz de la pharmacie', max_length=15)),
                ('reseau_paiement', models.CharField(choices=[('tmoney', 'T-Money'), ('flooz', 'Flooz')], default='tmoney', max_length=10)),
            ],
            bases=('lamessin_app.etablissementsante',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_texte', models.TextField()),
                ('envoye_par_utilisateur', models.BooleanField()),
                ('heure_message', models.DateTimeField(auto_now_add=True)),
                ('chatbot_associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lamessin_app.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('heure_envoi', models.DateTimeField(auto_now_add=True)),
                ('type_notification', models.CharField(max_length=50)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-heure_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateField(auto_now_add=True)),
                ('code_securite', models.CharField(max_length=15, null=True, unique=True)),
                ('fichier_ordonnance', models.FileField(blank=True, null=True, upload_to='ordonnances/pdf/')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.consultation')),
                ('medecin_prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medecin')),
                ('patient_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_boites', models.PositiveIntegerField(default=1)),
                ('posologie_specifique', models.TextField()),
                ('duree_traitement_jours', models.PositiveIntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='lamessin_app.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.FloatField()),
                ('moyen_de_paiement', models.CharField(max_length=50)),
                ('identifiant_transaction_mobile', models.CharField(max_length=100, unique=True)),
                ('confirmation_paiement', models.BooleanField(default=False)),
                ('commande_associee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.commande')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='rdv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='lamessin_app.rendezvous'),
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_traitement', models.CharField(max_length=100)),
                ('date_debut_traitement', models.DateField()),
                ('date_fin_traitement', models.DateField()),
                ('ordonnance_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.ordonnance')),
                ('patient_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PriseMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_prise_prevue', models.TimeField()),
                ('prise_effectuee', models.BooleanField(default=False)),
                ('date_prise_reelle', models.DateField()),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.traitement')),
            ],
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin_concerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medecin'),
        ),
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_consultation', models.PositiveIntegerField(default=60)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages', to='lamessin_app.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.patient'),
        ),
        migrations.AddField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_commandes', to='lamessin_app.patient'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle_en_stock', models.PositiveIntegerField()),
                ('seuil_alerte', models.PositiveIntegerField()),
                ('date_peremption', models.DateField()),
                ('produit_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament')),
                ('pharmacie_detentrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='lamessin_app.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.pharmacie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together={('medecin_concerne', 'date_rdv', 'heure_rdv')},
        ),
    ]
