# Generated by Django 6.0.2 on 2026-03-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamessin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date_rdv', '-heure_rdv']},
        ),
    ]
