# Generated by Django 6.0.2 on 2026-04-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamessin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacien',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.pharmacie'),
        ),
    ]
