# Generated by Django 6.0.2 on 2026-03-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamessin_app', '0002_alter_rendezvous_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['nom_commercial'], 'verbose_name': 'Médicament'},
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='posologie',
            new_name='posologie_standard',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='liste_medicaments_prescrits',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='code_securite',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='ordonnance_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.ordonnance'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom_commercial',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('actes_effectues', models.TextField()),
                ('notes_medecin', models.TextField(blank=True, null=True)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='lamessin_app.rendezvous')),
            ],
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamessin_app.consultation'),
        ),
        migrations.CreateModel(
            name='DetailOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_boites', models.PositiveIntegerField(default=1)),
                ('posologie_specifique', models.TextField()),
                ('duree_traitement_jours', models.PositiveIntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamessin_app.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='lamessin_app.ordonnance')),
            ],
        ),
    ]
