# Generated by Django 6.0.2 on 2026-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamessin_app', '0002_pharmacien_pharmacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
