# Generated by Django 6.0.2 on 2026-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamessin_app', '0003_alter_stock_seuil_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut_actuel_rdv',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirme'), ('annule', 'Annule'), ('termine', 'Termine'), ('expire', 'Expire')], default='en_attente', max_length=50),
        ),
    ]
